# Generated by Django 5.2.4 on 2026-07-22 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='Degree, department, or current designation', max_length=120)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('data-analyst', 'Data Analyst'), ('software-developer', 'Software Developer'), ('web-developer', 'Web Developer'), ('cloud-engineer', 'Cloud Engineer')], max_length=40)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('aptitude', 'Aptitude'), ('technical', 'Technical'), ('coding', 'Coding'), ('completed', 'Completed')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('technical', 'Technical'), ('coding', 'Coding')], max_length=20)),
                ('category', models.CharField(choices=[('quantitative', 'Quantitative'), ('logical', 'Logical reasoning'), ('verbal', 'Verbal ability'), ('non-verbal', 'Non-verbal reasoning'), ('technical', 'Technical'), ('coding', 'Coding')], max_length=30)),
                ('role', models.CharField(blank=True, choices=[('data-analyst', 'Data Analyst'), ('software-developer', 'Software Developer'), ('web-developer', 'Web Developer'), ('cloud-engineer', 'Cloud Engineer')], max_length=40)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('starter_code', models.JSONField(blank=True, default=dict)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('visible_test_count', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('technical', 'Technical'), ('coding', 'Coding')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('auto_submitted', 'Auto submitted')], default='in_progress', max_length=20)),
                ('question_ids', models.JSONField(default=list)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ProctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='assessments.attempt')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='assessments.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('code', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('timed_out', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('candidate', 'round_type'), name='unique_candidate_round'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_response'),
        ),
    ]
