# Generated by Django 5.2.4 on 2026-07-22 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hiring_status',
            field=models.CharField(choices=[('assessment_pending', 'Assessment pending'), ('assessment_completed', 'Assessment completed'), ('technical_scheduled', 'Technical interview scheduled'), ('technical_completed', 'Technical interview completed'), ('hr_scheduled', 'HR interview scheduled'), ('hr_completed', 'HR interview completed'), ('on_hold', 'On hold'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='assessment_pending', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hiring_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(choices=[('chennai', 'Chennai'), ('bengaluru', 'Bengaluru'), ('hyderabad', 'Hyderabad')], default='hyderabad', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('assessment_pending', 'Assessment pending'), ('assessment_completed', 'Assessment completed'), ('technical_scheduled', 'Technical interview scheduled'), ('technical_completed', 'Technical interview completed'), ('hr_scheduled', 'HR interview scheduled'), ('hr_completed', 'HR interview completed'), ('on_hold', 'On hold'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assessments.candidate')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
