# Generated by Django 5.2.4 on 2026-07-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_candidate_hiring_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(choices=[('not_provided', 'Not provided'), ('chennai', 'Chennai'), ('bengaluru', 'Bengaluru'), ('hyderabad', 'Hyderabad')], default='not_provided', max_length=20),
        ),
    ]
