# Generated by Django 5.2.4 on 2026-07-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_candidate_preferred_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('data-analyst', 'Data Analyst'), ('software-developer', 'Software Developer'), ('frontend-developer', 'Frontend Developer'), ('backend-developer', 'Backend Developer'), ('full-stack-developer', 'Full Stack Developer'), ('web-developer', 'Web Developer'), ('cloud-engineer', 'Cloud Engineer')], max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='role',
            field=models.CharField(blank=True, choices=[('data-analyst', 'Data Analyst'), ('software-developer', 'Software Developer'), ('frontend-developer', 'Frontend Developer'), ('backend-developer', 'Backend Developer'), ('full-stack-developer', 'Full Stack Developer'), ('web-developer', 'Web Developer'), ('cloud-engineer', 'Cloud Engineer')], max_length=40),
        ),
    ]
