# Generated by Django 5.2.4 on 2026-07-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_candidate_role_alter_question_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['started_at']},
        ),
    ]
