# Generated by Django 5.2.4 on 2026-08-13

from django.db import migrations, models


ROLE_CHOICES = [
    ("data-analyst", "Data Analyst"),
    ("mern-stack-developer", "MERN Stack Developer"),
    ("frontend-developer", "Frontend Developer"),
    ("backend-developer", "Backend Developer"),
    ("full-stack-developer", "Full Stack Developer"),
    ("web-developer", "Web Developer"),
    ("cloud-engineer", "Cloud Engineer"),
]


def replace_role(apps, schema_editor):
    Candidate = apps.get_model("assessments", "Candidate")
    Question = apps.get_model("assessments", "Question")
    Candidate.objects.filter(role="software-developer").update(role="mern-stack-developer")
    Question.objects.filter(role="software-developer").update(role="mern-stack-developer")


def restore_role(apps, schema_editor):
    Candidate = apps.get_model("assessments", "Candidate")
    Question = apps.get_model("assessments", "Question")
    Candidate.objects.filter(role="mern-stack-developer").update(role="software-developer")
    Question.objects.filter(role="mern-stack-developer").update(role="software-developer")


class Migration(migrations.Migration):
    dependencies = [("assessments", "0005_alter_attempt_options")]

    operations = [
        migrations.RunPython(replace_role, restore_role),
        migrations.AlterField(
            model_name="candidate",
            name="role",
            field=models.CharField(choices=ROLE_CHOICES, max_length=40),
        ),
        migrations.AlterField(
            model_name="question",
            name="role",
            field=models.CharField(blank=True, choices=ROLE_CHOICES, max_length=40),
        ),
    ]
