# Generated by Django 5.2.4 on 2026-08-18 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_replace_software_developer_with_mern_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_cycle', models.PositiveIntegerField()),
                ('status_before_reset', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='attempt',
            name='unique_candidate_round',
        ),
        migrations.AddField(
            model_name='attempt',
            name='assessment_cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='access_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('auto_submitted', 'Auto submitted'), ('terminated', 'Terminated after exit')], default='in_progress', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('candidate', 'round_type', 'assessment_cycle'), name='unique_candidate_round_cycle'),
        ),
        migrations.AddField(
            model_name='assessmentreset',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_resets', to='assessments.candidate'),
        ),
        migrations.AddField(
            model_name='assessmentreset',
            name='reset_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
